USE ROLE DBO_TRAINING_RAW_CONTRIBUTOR;
USE WAREHOUSE TRAINING_WH;

USE DATABASE TRAINING;
USE SCHEMA RAW;

TRUNCATE TABLE LENDER_HOLDINGS;

COPY INTO "TRAINING"."RAW"."LENDER_HOLDINGS"
  FROM @~/staged/
  FILES = ('lender_holdings_sample.csv.gz')
  FILE_FORMAT = FILE_FORMAT_CSV
  --VALIDATION_MODE = RETURN_ERRORS
  ON_ERROR=CONTINUE;


SELECT * 
FROM LENDER_HOLDINGS
LIMIT 100;